# Simple deployment used to deploy and manage the app in nigelpoulton/ps-web:1.0
# this is an eample deployment for vlumes using empty dir
apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-path-deploy
  labels:
    app: host-app
spec:
  selector:
    matchLabels:
      app: host-app
  replicas: 5
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: host-app
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: docker-pod
        image: docker
        command: ["sleep"]
        args: ["100000"]
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts: 
          - name: docker-socket
            mountPath: /var/run/docker.sock
        resources:
      volumes: 
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket